//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoCandidatos.ServiceGestao {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataSV", Namespace="http://schemas.datacontract.org/2004/07/WCFDAL.Contract")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GestaoCandidatos.ServiceGestao.ListaEntrevistasSV))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GestaoCandidatos.ServiceGestao.ListaEscalaAvaliacaoSV))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GestaoCandidatos.ServiceGestao.ListaTipoEscolaridadeSV))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GestaoCandidatos.ServiceGestao.ListaCandidatoSV))]
    public partial class DataSV : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HasRowsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasError {
            get {
                return this.HasErrorField;
            }
            set {
                if ((this.HasErrorField.Equals(value) != true)) {
                    this.HasErrorField = value;
                    this.RaisePropertyChanged("HasError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasRows {
            get {
                return this.HasRowsField;
            }
            set {
                if ((this.HasRowsField.Equals(value) != true)) {
                    this.HasRowsField = value;
                    this.RaisePropertyChanged("HasRows");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaEntrevistasSV", Namespace="http://schemas.datacontract.org/2004/07/WCFDAL.Contract")]
    [System.SerializableAttribute()]
    public partial class ListaEntrevistasSV : GestaoCandidatos.ServiceGestao.DataSV {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestaoCandidatos.ServiceGestao.EntrevistasSV[] ListaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestaoCandidatos.ServiceGestao.EntrevistasSV[] Lista {
            get {
                return this.ListaField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaField, value) != true)) {
                    this.ListaField = value;
                    this.RaisePropertyChanged("Lista");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaEscalaAvaliacaoSV", Namespace="http://schemas.datacontract.org/2004/07/WCFDAL.Contract")]
    [System.SerializableAttribute()]
    public partial class ListaEscalaAvaliacaoSV : GestaoCandidatos.ServiceGestao.DataSV {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestaoCandidatos.ServiceGestao.EscalaAvaliacaoSV[] ListaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestaoCandidatos.ServiceGestao.EscalaAvaliacaoSV[] Lista {
            get {
                return this.ListaField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaField, value) != true)) {
                    this.ListaField = value;
                    this.RaisePropertyChanged("Lista");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaTipoEscolaridadeSV", Namespace="http://schemas.datacontract.org/2004/07/WCFDAL.Contract")]
    [System.SerializableAttribute()]
    public partial class ListaTipoEscolaridadeSV : GestaoCandidatos.ServiceGestao.DataSV {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestaoCandidatos.ServiceGestao.TipoEscolaridadeSV[] ListaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestaoCandidatos.ServiceGestao.TipoEscolaridadeSV[] Lista {
            get {
                return this.ListaField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaField, value) != true)) {
                    this.ListaField = value;
                    this.RaisePropertyChanged("Lista");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListaCandidatoSV", Namespace="http://schemas.datacontract.org/2004/07/WCFDAL.Contract")]
    [System.SerializableAttribute()]
    public partial class ListaCandidatoSV : GestaoCandidatos.ServiceGestao.DataSV {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestaoCandidatos.ServiceGestao.CandidatoSV[] ListaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestaoCandidatos.ServiceGestao.CandidatoSV[] Lista {
            get {
                return this.ListaField;
            }
            set {
                if ((object.ReferenceEquals(this.ListaField, value) != true)) {
                    this.ListaField = value;
                    this.RaisePropertyChanged("Lista");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CandidatoSV", Namespace="http://schemas.datacontract.org/2004/07/WCFDAL.Contract")]
    [System.SerializableAttribute()]
    public partial class CandidatoSV : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataNascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EscolaridadeField;
        
        private string NifField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataNascimento {
            get {
                return this.DataNascimentoField;
            }
            set {
                if ((this.DataNascimentoField.Equals(value) != true)) {
                    this.DataNascimentoField = value;
                    this.RaisePropertyChanged("DataNascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Escolaridade {
            get {
                return this.EscolaridadeField;
            }
            set {
                if ((this.EscolaridadeField.Equals(value) != true)) {
                    this.EscolaridadeField = value;
                    this.RaisePropertyChanged("Escolaridade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Nif {
            get {
                return this.NifField;
            }
            set {
                if ((object.ReferenceEquals(this.NifField, value) != true)) {
                    this.NifField = value;
                    this.RaisePropertyChanged("Nif");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntrevistasSV", Namespace="http://schemas.datacontract.org/2004/07/WCFDAL.Contract")]
    [System.SerializableAttribute()]
    public partial class EntrevistasSV : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CandidatoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataHoraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntDescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EscaDescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdEntrevistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestaoCandidatos.ServiceGestao.CandidatoSV candidatoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GestaoCandidatos.ServiceGestao.EscalaAvaliacaoSV escalaAvaliacaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CandidatoId {
            get {
                return this.CandidatoIdField;
            }
            set {
                if ((this.CandidatoIdField.Equals(value) != true)) {
                    this.CandidatoIdField = value;
                    this.RaisePropertyChanged("CandidatoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataHora {
            get {
                return this.DataHoraField;
            }
            set {
                if ((this.DataHoraField.Equals(value) != true)) {
                    this.DataHoraField = value;
                    this.RaisePropertyChanged("DataHora");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntDescricao {
            get {
                return this.EntDescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.EntDescricaoField, value) != true)) {
                    this.EntDescricaoField = value;
                    this.RaisePropertyChanged("EntDescricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EscaDescricao {
            get {
                return this.EscaDescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.EscaDescricaoField, value) != true)) {
                    this.EscaDescricaoField = value;
                    this.RaisePropertyChanged("EscaDescricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEntrevista {
            get {
                return this.IdEntrevistaField;
            }
            set {
                if ((this.IdEntrevistaField.Equals(value) != true)) {
                    this.IdEntrevistaField = value;
                    this.RaisePropertyChanged("IdEntrevista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nota {
            get {
                return this.NotaField;
            }
            set {
                if ((object.ReferenceEquals(this.NotaField, value) != true)) {
                    this.NotaField = value;
                    this.RaisePropertyChanged("Nota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestaoCandidatos.ServiceGestao.CandidatoSV candidato {
            get {
                return this.candidatoField;
            }
            set {
                if ((object.ReferenceEquals(this.candidatoField, value) != true)) {
                    this.candidatoField = value;
                    this.RaisePropertyChanged("candidato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GestaoCandidatos.ServiceGestao.EscalaAvaliacaoSV escalaAvaliacao {
            get {
                return this.escalaAvaliacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.escalaAvaliacaoField, value) != true)) {
                    this.escalaAvaliacaoField = value;
                    this.RaisePropertyChanged("escalaAvaliacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EscalaAvaliacaoSV", Namespace="http://schemas.datacontract.org/2004/07/WCFDAL.Contract")]
    [System.SerializableAttribute()]
    public partial class EscalaAvaliacaoSV : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nota {
            get {
                return this.NotaField;
            }
            set {
                if ((object.ReferenceEquals(this.NotaField, value) != true)) {
                    this.NotaField = value;
                    this.RaisePropertyChanged("Nota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoEscolaridadeSV", Namespace="http://schemas.datacontract.org/2004/07/WCFDAL.Contract")]
    [System.SerializableAttribute()]
    public partial class TipoEscolaridadeSV : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceGestao.IServiceHR")]
    public interface IServiceHR {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/CriarCandidatos", ReplyAction="http://tempuri.org/IServiceHR/CriarCandidatosResponse")]
        string CriarCandidatos(string Nome, string Nif, System.DateTime DataNascimento, int Escolaridade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/CriarCandidatos", ReplyAction="http://tempuri.org/IServiceHR/CriarCandidatosResponse")]
        System.Threading.Tasks.Task<string> CriarCandidatosAsync(string Nome, string Nif, System.DateTime DataNascimento, int Escolaridade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/GetCandidatos", ReplyAction="http://tempuri.org/IServiceHR/GetCandidatosResponse")]
        GestaoCandidatos.ServiceGestao.ListaCandidatoSV GetCandidatos(string Nome, string Nif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/GetCandidatos", ReplyAction="http://tempuri.org/IServiceHR/GetCandidatosResponse")]
        System.Threading.Tasks.Task<GestaoCandidatos.ServiceGestao.ListaCandidatoSV> GetCandidatosAsync(string Nome, string Nif);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/UpdateCandidatos", ReplyAction="http://tempuri.org/IServiceHR/UpdateCandidatosResponse")]
        void UpdateCandidatos(int id, string Nome, string Nif, System.DateTime DataNascimento, int Escolaridade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/UpdateCandidatos", ReplyAction="http://tempuri.org/IServiceHR/UpdateCandidatosResponse")]
        System.Threading.Tasks.Task UpdateCandidatosAsync(int id, string Nome, string Nif, System.DateTime DataNascimento, int Escolaridade);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/DeleteCandidatos", ReplyAction="http://tempuri.org/IServiceHR/DeleteCandidatosResponse")]
        void DeleteCandidatos(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/DeleteCandidatos", ReplyAction="http://tempuri.org/IServiceHR/DeleteCandidatosResponse")]
        System.Threading.Tasks.Task DeleteCandidatosAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/CriarEntrevistas", ReplyAction="http://tempuri.org/IServiceHR/CriarEntrevistasResponse")]
        string CriarEntrevistas(int Id, System.DateTime HoraEntrevista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/CriarEntrevistas", ReplyAction="http://tempuri.org/IServiceHR/CriarEntrevistasResponse")]
        System.Threading.Tasks.Task<string> CriarEntrevistasAsync(int Id, System.DateTime HoraEntrevista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/GetEntrevistas", ReplyAction="http://tempuri.org/IServiceHR/GetEntrevistasResponse")]
        GestaoCandidatos.ServiceGestao.ListaEntrevistasSV GetEntrevistas(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/GetEntrevistas", ReplyAction="http://tempuri.org/IServiceHR/GetEntrevistasResponse")]
        System.Threading.Tasks.Task<GestaoCandidatos.ServiceGestao.ListaEntrevistasSV> GetEntrevistasAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/UpdateEntrevistas", ReplyAction="http://tempuri.org/IServiceHR/UpdateEntrevistasResponse")]
        void UpdateEntrevistas(int Id, System.DateTime HoraEntrevista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/UpdateEntrevistas", ReplyAction="http://tempuri.org/IServiceHR/UpdateEntrevistasResponse")]
        System.Threading.Tasks.Task UpdateEntrevistasAsync(int Id, System.DateTime HoraEntrevista);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/DeleteEntrevistas", ReplyAction="http://tempuri.org/IServiceHR/DeleteEntrevistasResponse")]
        void DeleteEntrevistas(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/DeleteEntrevistas", ReplyAction="http://tempuri.org/IServiceHR/DeleteEntrevistasResponse")]
        System.Threading.Tasks.Task DeleteEntrevistasAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/AddAvaliacaoEntrevista", ReplyAction="http://tempuri.org/IServiceHR/AddAvaliacaoEntrevistaResponse")]
        void AddAvaliacaoEntrevista(int IdEntrevista, int IdEscalaAval, string Desc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/AddAvaliacaoEntrevista", ReplyAction="http://tempuri.org/IServiceHR/AddAvaliacaoEntrevistaResponse")]
        System.Threading.Tasks.Task AddAvaliacaoEntrevistaAsync(int IdEntrevista, int IdEscalaAval, string Desc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/GetEscalaAvaliacao", ReplyAction="http://tempuri.org/IServiceHR/GetEscalaAvaliacaoResponse")]
        GestaoCandidatos.ServiceGestao.ListaEscalaAvaliacaoSV GetEscalaAvaliacao();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/GetEscalaAvaliacao", ReplyAction="http://tempuri.org/IServiceHR/GetEscalaAvaliacaoResponse")]
        System.Threading.Tasks.Task<GestaoCandidatos.ServiceGestao.ListaEscalaAvaliacaoSV> GetEscalaAvaliacaoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/GetTipoescolaridade", ReplyAction="http://tempuri.org/IServiceHR/GetTipoescolaridadeResponse")]
        GestaoCandidatos.ServiceGestao.ListaTipoEscolaridadeSV GetTipoescolaridade();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceHR/GetTipoescolaridade", ReplyAction="http://tempuri.org/IServiceHR/GetTipoescolaridadeResponse")]
        System.Threading.Tasks.Task<GestaoCandidatos.ServiceGestao.ListaTipoEscolaridadeSV> GetTipoescolaridadeAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceHRChannel : GestaoCandidatos.ServiceGestao.IServiceHR, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceHRClient : System.ServiceModel.ClientBase<GestaoCandidatos.ServiceGestao.IServiceHR>, GestaoCandidatos.ServiceGestao.IServiceHR {
        
        public ServiceHRClient() {
        }
        
        public ServiceHRClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceHRClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHRClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceHRClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CriarCandidatos(string Nome, string Nif, System.DateTime DataNascimento, int Escolaridade) {
            return base.Channel.CriarCandidatos(Nome, Nif, DataNascimento, Escolaridade);
        }
        
        public System.Threading.Tasks.Task<string> CriarCandidatosAsync(string Nome, string Nif, System.DateTime DataNascimento, int Escolaridade) {
            return base.Channel.CriarCandidatosAsync(Nome, Nif, DataNascimento, Escolaridade);
        }
        
        public GestaoCandidatos.ServiceGestao.ListaCandidatoSV GetCandidatos(string Nome, string Nif) {
            return base.Channel.GetCandidatos(Nome, Nif);
        }
        
        public System.Threading.Tasks.Task<GestaoCandidatos.ServiceGestao.ListaCandidatoSV> GetCandidatosAsync(string Nome, string Nif) {
            return base.Channel.GetCandidatosAsync(Nome, Nif);
        }
        
        public void UpdateCandidatos(int id, string Nome, string Nif, System.DateTime DataNascimento, int Escolaridade) {
            base.Channel.UpdateCandidatos(id, Nome, Nif, DataNascimento, Escolaridade);
        }
        
        public System.Threading.Tasks.Task UpdateCandidatosAsync(int id, string Nome, string Nif, System.DateTime DataNascimento, int Escolaridade) {
            return base.Channel.UpdateCandidatosAsync(id, Nome, Nif, DataNascimento, Escolaridade);
        }
        
        public void DeleteCandidatos(int id) {
            base.Channel.DeleteCandidatos(id);
        }
        
        public System.Threading.Tasks.Task DeleteCandidatosAsync(int id) {
            return base.Channel.DeleteCandidatosAsync(id);
        }
        
        public string CriarEntrevistas(int Id, System.DateTime HoraEntrevista) {
            return base.Channel.CriarEntrevistas(Id, HoraEntrevista);
        }
        
        public System.Threading.Tasks.Task<string> CriarEntrevistasAsync(int Id, System.DateTime HoraEntrevista) {
            return base.Channel.CriarEntrevistasAsync(Id, HoraEntrevista);
        }
        
        public GestaoCandidatos.ServiceGestao.ListaEntrevistasSV GetEntrevistas(int Id) {
            return base.Channel.GetEntrevistas(Id);
        }
        
        public System.Threading.Tasks.Task<GestaoCandidatos.ServiceGestao.ListaEntrevistasSV> GetEntrevistasAsync(int Id) {
            return base.Channel.GetEntrevistasAsync(Id);
        }
        
        public void UpdateEntrevistas(int Id, System.DateTime HoraEntrevista) {
            base.Channel.UpdateEntrevistas(Id, HoraEntrevista);
        }
        
        public System.Threading.Tasks.Task UpdateEntrevistasAsync(int Id, System.DateTime HoraEntrevista) {
            return base.Channel.UpdateEntrevistasAsync(Id, HoraEntrevista);
        }
        
        public void DeleteEntrevistas(int id) {
            base.Channel.DeleteEntrevistas(id);
        }
        
        public System.Threading.Tasks.Task DeleteEntrevistasAsync(int id) {
            return base.Channel.DeleteEntrevistasAsync(id);
        }
        
        public void AddAvaliacaoEntrevista(int IdEntrevista, int IdEscalaAval, string Desc) {
            base.Channel.AddAvaliacaoEntrevista(IdEntrevista, IdEscalaAval, Desc);
        }
        
        public System.Threading.Tasks.Task AddAvaliacaoEntrevistaAsync(int IdEntrevista, int IdEscalaAval, string Desc) {
            return base.Channel.AddAvaliacaoEntrevistaAsync(IdEntrevista, IdEscalaAval, Desc);
        }
        
        public GestaoCandidatos.ServiceGestao.ListaEscalaAvaliacaoSV GetEscalaAvaliacao() {
            return base.Channel.GetEscalaAvaliacao();
        }
        
        public System.Threading.Tasks.Task<GestaoCandidatos.ServiceGestao.ListaEscalaAvaliacaoSV> GetEscalaAvaliacaoAsync() {
            return base.Channel.GetEscalaAvaliacaoAsync();
        }
        
        public GestaoCandidatos.ServiceGestao.ListaTipoEscolaridadeSV GetTipoescolaridade() {
            return base.Channel.GetTipoescolaridade();
        }
        
        public System.Threading.Tasks.Task<GestaoCandidatos.ServiceGestao.ListaTipoEscolaridadeSV> GetTipoescolaridadeAsync() {
            return base.Channel.GetTipoescolaridadeAsync();
        }
    }
}
