//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoCandidatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidato
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Nif { get; set; }
        public System.DateTime DataNasc { get; set; }
        public int TipoEscolaridadeId { get; set; }
    
        public virtual TipoEscolaridade TipoEscolaridade { get; set; }
    }
}
