//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestaoCandidatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrevistas
    {
        public int Id { get; set; }
        public int CandidatoId { get; set; }
        public System.DateTime DataHora { get; set; }
        public Nullable<int> EscalaAvaliacaoId { get; set; }
        public string Descricao { get; set; }
    
        public virtual EscalaAvaliacao EscalaAvaliacao { get; set; }
    }
}
